# -*- coding: utf-8 -*-
"""eval×winrate+diff×credit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G32Os0j_wFr4NwNSDa2-MuGDgjgO8wIW
"""

# -*- coding: utf-8 -*-
# eval×winrate + diff×credit
# memory efficient + vectorized operations

# Cell 1: Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# Cell 2: Compile Fairy Stockfish
import os

fairy_path = "/content/drive/MyDrive/trees/fairy_stockfish"

if os.path.exists(fairy_path):
    print("Fairy Stockfish exists")
else:
    print("Compiling Fairy Stockfish...")
    !git clone https://github.com/fairy-stockfish/Fairy-Stockfish.git /content/Fairy-Stockfish
    !cd /content/Fairy-Stockfish/src && make build ARCH=x86-64-modern all=yes -j4
    !mkdir -p /content/drive/MyDrive/trees
    !cp /content/Fairy-Stockfish/src/stockfish {fairy_path}
    !chmod +x {fairy_path}
    print(f"Done: {fairy_path}")

# Cell 3: Setup
import os, shutil
from pathlib import Path
import numpy as np
import time

ENGINE       = '/content/fairy_stockfish'
VARIANT      = 'tinyhouse'  #@param ['chess', 'atomic', 'antichess', 'crazyhouse', '3check', 'racingkings', 'horde', 'tinyhouse']
THREADS      = 2            #@param {type:'integer'}
HASHMB       = 4096         #@param {type:'integer'}
DEPTH        = 5            #@param {type:'integer'}

THRESHOLD_CP = 1024         #@param {type:'integer'}

DRIVE_DIR = '/content/drive/MyDrive/trees'
DIR = f'{DRIVE_DIR}/{VARIANT}/'
os.makedirs(DIR, exist_ok=True)

EPD = f'{VARIANT}_credit.epd'

shutil.copy(f'{DRIVE_DIR}/fairy_stockfish', ENGINE)
os.chmod(ENGINE, 0o755)

INI = None
if os.path.exists(f'{DRIVE_DIR}/variants.ini'):
    shutil.copy(f'{DRIVE_DIR}/variants.ini', '/content/variants.ini')
    INI = '/content/variants.ini'

NNUE = None
for file in Path(DIR).glob('*.nnue'):
    shutil.copy(file, '/content/')
    NNUE = f'/content/{file.name}'
    break

if os.path.exists(f'{DIR}{EPD}'):
    shutil.copy(f'{DIR}{EPD}', f'/content/{EPD}')

print(f"Engine: {ENGINE}")
print(f"Variant: {VARIANT}")
print(f"NNUE: {NNUE or 'None'}")
print(f"INI: {INI or 'None'}")

# Cell 4: Engine class
import subprocess

class Engine:
    def __init__(self):
        self.process = subprocess.Popen(
            [ENGINE],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            bufsize=0
        )

        self.send_command('uci')
        self.read_until('uciok')

        if INI:
            self.send_command(f'load {INI}')
        self.send_command(f'setoption name UCI_Variant value {VARIANT}')

        if NNUE:
            self.send_command(f'setoption name EvalFile value {NNUE}')
            self.send_command('setoption name Use NNUE value true')

        self.send_command(f'setoption name Threads value {THREADS}')
        self.send_command(f'setoption name Hash value {HASHMB}')
        self.send_command('setoption name MultiPV value 1')
        self.send_command('setoption name UCI_AnalyseMode value true')

    def send_command(self, command: str):
        if self.process.poll() is None:
            try:
                self.process.stdin.write(f'{command}\n')
                self.process.stdin.flush()
            except (OSError, BrokenPipeError, ValueError):
                pass

    def read_until(self, terminator: str) -> list[str]:
        lines = []
        while True:
            line = self.process.stdout.readline().strip()
            if not line and self.process.poll() is not None:
                break
            lines.append(line)
            if terminator in line:
                break
        return lines

    def get_fen(self, position_cmd: str = 'position startpos') -> str:
        self.send_command(position_cmd)
        self.send_command('d')
        for line in self.read_until('Fen:'):
            if 'Fen:' in line:
                return ' '.join(line.split()[1:3])
        raise RuntimeError(f'Failed to get FEN for: {position_cmd}')

    def get_perft_moves(self, fen: str) -> list[str]:
        self.send_command(f'position fen {fen}')
        self.send_command('go perft 1')
        lines = self.read_until('Nodes searched:')

        moves = []
        for line in lines:
            if ':' in line and not line.startswith('Nodes'):
                move = line.split(':')[0].strip()
                moves.append(move)
        return moves

    def get_best_move(self, fen: str, searchmoves: list[str] = None) -> tuple[str, int] | None:
        self.send_command(f'position fen {fen}')

        cmd = f'go depth {DEPTH}'
        if searchmoves:
            cmd += ' searchmoves ' + ' '.join(searchmoves)

        self.send_command(cmd)
        lines = self.read_until('bestmove')

        best_move = None
        for line in reversed(lines):
            if line.startswith('bestmove'):
                if '(none)' in line:
                    return None
                best_move = line.split()[1]
                break

        if not best_move:
            return None

        for line in reversed(lines):
            if line.startswith('info') and 'score' in line:
                parts = line.split()
                for i, part in enumerate(parts):
                    if part == 'score' and i + 2 < len(parts):
                        score_type = parts[i + 1]
                        score_value = int(parts[i + 2])
                        if score_type == 'cp':
                            return (best_move, score_value)
                        elif score_type == 'mate':
                            score = (30000 - score_value) if score_value > 0 else (-30000 - score_value)
                            return (best_move, score)

        return None

    def shut_down(self):
        if self.process.poll() is None:
            try:
                self.send_command('quit')
            except (OSError, BrokenPipeError):
                pass
            self.process.terminate()
            self.process.wait()

# Cell 5: Tree class
class Tree:
    EDGE_DTYPE = np.dtype([
        ('move', 'S5'),
        ('eval', '<i2'),
        ('child', '<i4'),
        ('wins', '<u4'),
        ('losses', '<u4'),
        ('credits', '<u2'),
    ])

    def __init__(self):
        self.engine = Engine()

        self.node_fen = None
        self.node_offset = None
        self.node_num_edges = None
        self.node_all_moves = None
        self.edges = None

        self.node_count = 0
        self.node_capacity = 0
        self.edge_count = 0
        self.edge_capacity = 0
        self.root_id = 0

        self.fen_to_id = {}
        self.free_ids = None
        self.free_count = 0

        self.load_epd()
        self.print_memory()

    def print_memory(self):
        node_mem = (self.node_fen.nbytes + self.node_offset.nbytes +
                    self.node_num_edges.nbytes + self.node_all_moves.nbytes)
        edge_mem = self.edges.nbytes
        print(f"Node arrays: {node_mem / 1e9:.2f} GB")
        print(f"Edge buffer: {edge_mem / 1e9:.2f} GB")
        print(f"Total arrays: {(node_mem + edge_mem) / 1e9:.2f} GB")
        print(f"Nodes: {self.node_count:,}, Edges: {self.edge_count:,}, Free slots: {self.free_count:,}")

    def load_epd(self):
        epd_path = Path(EPD)
        if not epd_path.exists():
            print('Creating new tree\n')
            self.node_capacity = 100_000
            self.edge_capacity = 200_000
            self.node_fen = np.zeros(self.node_capacity, dtype='S28')
            self.node_offset = np.zeros(self.node_capacity, dtype=np.uint32)
            self.node_num_edges = np.zeros(self.node_capacity, dtype=np.uint8)
            self.node_all_moves = np.zeros(self.node_capacity, dtype=np.bool_)
            self.edges = np.zeros(self.edge_capacity, dtype=self.EDGE_DTYPE)
            self.free_ids = np.array([], dtype=np.int32)
            self.free_count = 0

            root_fen = self.engine.get_fen()
            self.root_id, _ = self.create_node(root_fen)
            return

        t0 = time.time()

        file_size = epd_path.stat().st_size
        with open(epd_path, 'rb') as f:
            f.seek(max(-500, -file_size), 2)
            last_lines = f.read().decode('utf-8').strip().split('\n')
            max_id = int(last_lines[-1].split(';')[0])

        self.node_count = max_id + 1
        self.node_capacity = self.node_count + 2_000_000
        self.edge_capacity = self.node_count * 4

        print(f"Allocating: {self.node_capacity:,} nodes, {self.edge_capacity:,} edges...")

        self.node_fen = np.zeros(self.node_capacity, dtype='S28')
        self.node_offset = np.zeros(self.node_capacity, dtype=np.uint32)
        self.node_num_edges = np.zeros(self.node_capacity, dtype=np.uint8)
        self.node_all_moves = np.zeros(self.node_capacity, dtype=np.bool_)
        self.edges = np.zeros(self.edge_capacity, dtype=self.EDGE_DTYPE)

        node_exists = np.zeros(self.node_count, dtype=np.bool_)

        print("Loading data...")

        self.edge_count = 0
        node_count_file = 0
        with open(epd_path, 'r') as f:
            for line in f:
                if not line.strip():
                    continue

                parts = line.rstrip().split(';')

                node_id = int(parts[0])
                fen = parts[1]
                moves = parts[2].split(',') if parts[2] else []
                evals = parts[3].split(',') if parts[3] else []
                child_ids = parts[4].split(',') if parts[4] else []
                wins = parts[5].split(',') if parts[5] else []
                losses = parts[6].split(',') if parts[6] else []
                credits = parts[7].split(',') if parts[7] else []
                all_moves = parts[8] == '1'

                node_exists[node_id] = True
                self.node_fen[node_id] = fen.encode('utf-8')
                self.node_offset[node_id] = self.edge_count
                self.node_num_edges[node_id] = len(moves)
                self.node_all_moves[node_id] = all_moves
                self.fen_to_id[fen] = node_id

                if self.edge_count + len(moves) >= self.edge_capacity:
                    self.ensure_edge_capacity(len(moves))

                for i, move in enumerate(moves):
                    self.edges[self.edge_count] = (
                        move.encode('utf-8'),
                        int(evals[i]) if i < len(evals) else 0,
                        int(child_ids[i]) if i < len(child_ids) else -1,
                        int(wins[i]) if i < len(wins) else 1,
                        int(losses[i]) if i < len(losses) else 1,
                        int(credits[i]) if i < len(credits) else 0,
                    )
                    self.edge_count += 1

                node_count_file += 1
        self.free_ids = np.nonzero(~node_exists)[0].astype(np.int32)
        self.free_count = len(self.free_ids)

        print(f'Loaded {node_count_file:,} nodes, {self.edge_count:,} edges, {self.free_count:,} holes ({time.time()-t0:.1f}s)\n')

    def save_epd(self):
        print("Finding reachable nodes...")
        t0 = time.time()

        reachable = np.zeros(self.node_count, dtype=np.bool_)
        reachable[self.root_id] = True
        queue = [self.root_id]

        while queue:
            node_id = queue.pop()
            offset = int(self.node_offset[node_id])
            num = int(self.node_num_edges[node_id])

            if num > 0:
                children = self.edges[offset:offset+num]['child']
                for child_id in children:
                    if child_id >= 0 and not reachable[child_id]:
                        reachable[child_id] = True
                        queue.append(child_id)

        reachable_count = int(reachable.sum())
        print(f"Found {reachable_count:,} reachable nodes ({time.time()-t0:.1f}s)")

        print("Saving...")
        t0 = time.time()

        temp_path = Path(EPD + '.tmp')
        epd_path = Path(EPD)

        live_edges = 0
        reachable_ids = np.nonzero(reachable)[0]

        with open(temp_path, 'w', newline='\n') as f:
            for node_id in reachable_ids:
                fen = self.node_fen[node_id].decode('utf-8')
                all_moves = '1' if self.node_all_moves[node_id] else '0'

                offset = int(self.node_offset[node_id])
                num = int(self.node_num_edges[node_id])
                live_edges += num

                if num > 0:
                    e = self.edges[offset:offset+num]
                    moves = ','.join(m.decode('utf-8') for m in e['move'])
                    evals = ','.join(str(x) for x in e['eval'])
                    child_ids = ','.join(str(x) for x in e['child'])
                    wins = ','.join(str(x) for x in e['wins'])
                    losses = ','.join(str(x) for x in e['losses'])
                    credits = ','.join(str(x) for x in e['credits'])
                else:
                    moves = evals = child_ids = wins = losses = credits = ''

                f.write(f"{node_id};{fen};{moves};{evals};{child_ids};{wins};{losses};{credits};{all_moves};\n")

        os.replace(temp_path, epd_path)

        frag = (self.edge_count - live_edges) / self.edge_count * 100 if self.edge_count > 0 else 0
        print(f'Saved {reachable_count:,} nodes, {live_edges:,} edges (frag: {frag:.1f}%) ({time.time()-t0:.1f}s)\n')

    def ensure_node_capacity(self):
        if self.node_count >= self.node_capacity:
            new_cap = self.node_capacity * 2
            print(f"Reallocating nodes: {new_cap:,}")

            new_fen = np.zeros(new_cap, dtype='S28')
            new_offset = np.zeros(new_cap, dtype=np.uint32)
            new_num = np.zeros(new_cap, dtype=np.uint8)
            new_all = np.zeros(new_cap, dtype=np.bool_)

            new_fen[:self.node_capacity] = self.node_fen
            new_offset[:self.node_capacity] = self.node_offset
            new_num[:self.node_capacity] = self.node_num_edges
            new_all[:self.node_capacity] = self.node_all_moves

            self.node_fen = new_fen
            self.node_offset = new_offset
            self.node_num_edges = new_num
            self.node_all_moves = new_all
            self.node_capacity = new_cap

    def ensure_edge_capacity(self, needed: int):
        if self.edge_count + needed >= self.edge_capacity:
            new_cap = max(self.edge_capacity * 2, self.edge_count + needed + 1_000_000)
            print(f"Reallocating edges: {new_cap:,}")

            new_edges = np.zeros(new_cap, dtype=self.EDGE_DTYPE)
            new_edges[:self.edge_count] = self.edges[:self.edge_count]
            self.edges = new_edges
            self.edge_capacity = new_cap

    def get_node_id(self) -> int:
        if self.free_count > 0:
            self.free_count -= 1
            return int(self.free_ids[self.free_count])
        self.ensure_node_capacity()
        node_id = self.node_count
        self.node_count += 1
        return node_id

    def add_edge(self, node_id: int, move: str, eval_cp: int, child_id: int = -1):
        old_offset = int(self.node_offset[node_id])
        old_num = int(self.node_num_edges[node_id])

        self.ensure_edge_capacity(old_num + 1)
        new_offset = self.edge_count

        if old_num > 0:
            self.edges[new_offset:new_offset + old_num] = self.edges[old_offset:old_offset + old_num]

        self.edges[new_offset + old_num] = (move.encode('utf-8'), eval_cp, child_id, 1, 1, 0)

        self.node_offset[node_id] = new_offset
        self.node_num_edges[node_id] = old_num + 1
        self.edge_count += old_num + 1

    def create_node(self, fen: str) -> tuple[int | None, int | None]:
        result = self.engine.get_best_move(fen)

        if result is None or abs(result[1]) > 29000:
            return (None, result[1] if result else 29999)

        best_move, best_score = result
        all_legal = self.engine.get_perft_moves(fen)

        node_id = self.get_node_id()

        self.ensure_edge_capacity(1)

        self.node_fen[node_id] = fen.encode('utf-8')
        self.node_offset[node_id] = self.edge_count
        self.node_num_edges[node_id] = 1
        self.node_all_moves[node_id] = len(all_legal) == 1

        self.edges[self.edge_count] = (best_move.encode('utf-8'), best_score, -1, 1, 1, 0)
        self.edge_count += 1

        self.fen_to_id[fen] = node_id
        return (node_id, None)

    def get_moves(self, node_id: int) -> list[str]:
        offset = int(self.node_offset[node_id])
        num = int(self.node_num_edges[node_id])
        return [self.edges[offset + i]['move'].decode('utf-8') for i in range(num)]

    def expand_move(self, node_id: int, edge_idx: int) -> int | None:
        offset = int(self.node_offset[node_id])

        child_id = int(self.edges[offset + edge_idx]['child'])
        if child_id >= 0:
            return child_id

        fen = self.node_fen[node_id].decode('utf-8')
        move = self.edges[offset + edge_idx]['move'].decode('utf-8')
        child_fen = self.engine.get_fen(f'position fen {fen} moves {move}')

        if child_fen in self.fen_to_id:
            child_id = self.fen_to_id[child_fen]
            self.edges[offset + edge_idx]['child'] = child_id
            return child_id

        child_id, mate_eval = self.create_node(child_fen)

        if child_id is None:
            self.edges[offset + edge_idx]['child'] = -2
            negamax = -mate_eval
            if negamax > 0:
                negamax -= 1
            elif negamax < 0:
                negamax += 1
            self.edges[offset + edge_idx]['eval'] = negamax
            return None

        self.edges[offset + edge_idx]['child'] = child_id
        return child_id

    def add_alternative(self, node_id: int):
        if self.node_all_moves[node_id]:
            return

        fen = self.node_fen[node_id].decode('utf-8')
        all_legal = self.engine.get_perft_moves(fen)
        analyzed = set(self.get_moves(node_id))
        unanalyzed = [m for m in all_legal if m not in analyzed]

        if not unanalyzed:
            self.node_all_moves[node_id] = True
            return

        result = self.engine.get_best_move(fen, searchmoves=unanalyzed)
        if result is None:
            self.node_all_moves[node_id] = True
            return

        move, move_eval = result
        child_id = -2 if abs(move_eval) > 29000 else -1
        self.add_edge(node_id, move, move_eval, child_id)

        if self.node_num_edges[node_id] == len(all_legal):
            self.node_all_moves[node_id] = True

    def backprop(self, node_id: int):
        offset = int(self.node_offset[node_id])
        num = int(self.node_num_edges[node_id])

        if num == 0:
            return

        edges = self.edges[offset:offset + num]

        for i in range(num):
            child_id = int(edges[i]['child'])
            if child_id < 0:
                continue

            child_offset = int(self.node_offset[child_id])
            child_num = int(self.node_num_edges[child_id])
            if child_num == 0:
                continue

            max_eval = int(self.edges[child_offset:child_offset + child_num]['eval'].max())

            new_eval = -max_eval
            if new_eval > 0:
                new_eval -= 1
            elif new_eval < 0:
                new_eval += 1

            self.edges[offset + i]['eval'] = new_eval

            if abs(new_eval) > 29000:
                self.edges[offset + i]['child'] = -2

    def walker(self, bestline=False):
        node_id = self.root_id
        path = []
        visited = set()
        ply = 0
        result = 0
        output = []

        while True:
            offset = int(self.node_offset[node_id])
            num = int(self.node_num_edges[node_id])

            # Slice pre vektorizáciu
            edges = self.edges[offset:offset + num]
            evals = edges['eval'].astype(np.int32)

            best_eval = int(evals.max())

            # Mate check
            if abs(best_eval) > 29000:
                best_edge_idx = int(np.argmax(evals))
                path.append((node_id, best_edge_idx))
                result = 1 if best_eval > 0 else -1
                mate_dist = 30000 - abs(best_eval)
                sign = 'M+' if best_eval > 0 else 'M-'
                output.append(f"{sign}{mate_dist}")
                break

            # Selekcia
            if bestline:
                best_edge_idx = int(np.argmax(evals))
            else:
                children = edges['child'].astype(np.int32)
                wins = edges['wins'].astype(np.int64)
                losses = edges['losses'].astype(np.int64)
                credits = edges['credits'].astype(np.int32)

                valid = children != -2

                eval_norm = 256 * (THRESHOLD_CP + evals - best_eval - 1) // THRESHOLD_CP
                winrate = 256 * wins // (wins + losses)
                diff = np.abs(eval_norm - winrate)
                scores = eval_norm * winrate + diff * credits

                scores = np.where(valid, scores, -30000)
                best_edge_idx = int(np.argmax(scores))

            edge_eval = int(self.edges[offset + best_edge_idx]['eval'])

            # Loop detection
            if edge_eval == 0:
                if node_id in visited:
                    output.append("∞")
                    break
                visited.add(node_id)

            # Shift eval
            if edge_eval > 0:
                self.edges[offset + best_edge_idx]['eval'] = edge_eval - 1
            elif edge_eval < 0:
                self.edges[offset + best_edge_idx]['eval'] = edge_eval + 1

            path.append((node_id, best_edge_idx))

            move = edges[best_edge_idx]['move'].decode('utf-8')
            new_eval = int(self.edges[offset + best_edge_idx]['eval'])
            if ply % 2 == 0:
                output.append(f"{ply//2 + 1}.")
            output.append(f"{move} {new_eval:+d}")

            child_id = int(edges[best_edge_idx]['child'])

            if child_id == -1:
                if not self.node_all_moves[node_id]:
                    self.add_alternative(node_id)
                child_id = self.expand_move(node_id, best_edge_idx)
                if child_id is None:
                    ev = int(self.edges[offset + best_edge_idx]['eval'])
                    result = 1 if ev > 0 else -1
                    mate_dist = 30000 - abs(ev)
                    sign = 'M+' if ev > 0 else 'M-'
                    output.append(f"{sign}{mate_dist}")
                    break

            node_id = child_id
            ply += 1

        output_str = ' '.join(output)

        if not path:
            return output_str

        # Backprop
        for node_id, edge_idx in reversed(path):
            offset = int(self.node_offset[node_id])
            num = int(self.node_num_edges[node_id])

            self.edges[offset + edge_idx]['wins'] += 1 + result
            self.edges[offset + edge_idx]['losses'] += 1 - result

            # Credit update
            edges = self.edges[offset:offset + num]
            edges['credits'] = np.where(
                np.arange(num) == edge_idx, 0,
                np.where(edges['child'] != -2, edges['credits'] + 1, edges['credits'])
            )

            self.backprop(node_id)
            result = -result

        return output_str

    def explore(self):
        try:
            cycle = 0
            while True:
                cycle += 1
                output = self.walker(bestline=(cycle % 4096 == 0))
                if cycle % 1024 == 0:
                    print(f"[{cycle}] {output}")
                if cycle % 65536 == 0:
                    self.save_epd()
                    shutil.copy(f'/content/{EPD}', f'{DIR}{EPD}')
        except KeyboardInterrupt:
            print('\nInterrupted')
        finally:
            print("Final backprop...")
            # Len reachable
            reachable = np.zeros(self.node_count, dtype=np.bool_)
            reachable[self.root_id] = True
            queue = [self.root_id]
            while queue:
                nid = queue.pop()
                off = int(self.node_offset[nid])
                n = int(self.node_num_edges[nid])
                if n > 0:
                    for cid in self.edges[off:off+n]['child']:
                        if cid >= 0 and not reachable[cid]:
                            reachable[cid] = True
                            queue.append(cid)

            for node_id in np.nonzero(reachable)[0][::-1]:
                self.backprop(node_id)

            self.save_epd()
            shutil.copy(f'/content/{EPD}', f'{DIR}{EPD}')
            self.engine.shut_down()

# Cell 6: Run
tree = Tree()
tree.explore()