# -*- coding: utf-8 -*-
"""YoYo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17L7BiRBbwJXNmjGZXJ7Hay4iRN_UPke7
"""

# Cell 1: Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# Cell 2: Compile Fairy Stockfish
import os

fairy_path = "/content/drive/MyDrive/trees/fairy_stockfish"

if os.path.exists(fairy_path):
    print("Fairy Stockfish exists")
else:
    print("Compiling Fairy Stockfish...")
    !git clone https://github.com/fairy-stockfish/Fairy-Stockfish.git /content/Fairy-Stockfish
    !cd /content/Fairy-Stockfish/src && make build ARCH=x86-64-modern all=yes -j4
    !mkdir -p /content/drive/MyDrive/trees
    !cp /content/Fairy-Stockfish/src/stockfish {fairy_path}
    !chmod +x {fairy_path}
    print(f"Done: {fairy_path}")

# Cell 3: Setup
import os, shutil
from pathlib import Path
import numpy as np
import time

ENGINE       = '/content/fairy_stockfish'
VARIANT      = 'tinyhouse'  #@param ['chess', 'atomic', 'tinyhouse']
THREADS      = 2            #@param {type:'integer'}
HASHMB       = 4096         #@param {type:'integer'}
DEPTH        = 5            #@param {type:'integer'}

DRIVE_DIR = '/content/drive/MyDrive/trees'
DIR = f'{DRIVE_DIR}/{VARIANT}/'
os.makedirs(DIR, exist_ok=True)

EPD = f'{VARIANT}_yoyo.epd'

shutil.copy(f'{DRIVE_DIR}/fairy_stockfish', ENGINE)
os.chmod(ENGINE, 0o755)

INI = None
if os.path.exists(f'{DRIVE_DIR}/variants.ini'):
    shutil.copy(f'{DRIVE_DIR}/variants.ini', '/content/variants.ini')
    INI = '/content/variants.ini'

NNUE = None
for file in Path(DIR).glob('*.nnue'):
    shutil.copy(file, '/content/')
    NNUE = f'/content/{file.name}'
    break

if os.path.exists(f'{DIR}{EPD}'):
    shutil.copy(f'{DIR}{EPD}', f'/content/{EPD}')

print(f"Engine: {ENGINE}")
print(f"Variant: {VARIANT}")
print(f"NNUE: {NNUE or 'None'}")

# Cell 4: Engine class
import subprocess

class Engine:
    """Interface to Fairy Stockfish chess engine via UCI protocol.
    
    Manages communication with the engine for position analysis,
    move generation, and evaluation.
    """
    def __init__(self):
        self.process = subprocess.Popen(
            [ENGINE],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            bufsize=0
        )
        self.send_command('uci')
        self.read_until('uciok')

        if INI:
            self.send_command(f'load {INI}')
        self.send_command(f'setoption name UCI_Variant value {VARIANT}')

        if NNUE:
            self.send_command(f'setoption name EvalFile value {NNUE}')
            self.send_command('setoption name Use NNUE value true')

        self.send_command(f'setoption name Threads value {THREADS}')
        self.send_command(f'setoption name Hash value {HASHMB}')

    def send_command(self, command: str):
        if self.process.poll() is None:
            self.process.stdin.write(f'{command}\n')
            self.process.stdin.flush()

    def read_until(self, terminator: str) -> list[str]:
        lines = []
        while True:
            line = self.process.stdout.readline().strip()
            if not line and self.process.poll() is not None:
                break
            lines.append(line)
            if terminator in line:
                break
        return lines

    def get_fen(self, position_cmd: str = 'position startpos') -> str:
        self.send_command(position_cmd)
        self.send_command('d')
        for line in self.read_until('Fen:'):
            if 'Fen:' in line:
                return ' '.join(line.split()[1:3])
        raise RuntimeError(f'Failed to get FEN')

    def get_perft_moves(self, fen: str) -> list[str]:
        self.send_command(f'position fen {fen}')
        self.send_command('go perft 1')
        lines = self.read_until('Nodes searched:')
        moves = []
        for line in lines:
            if ':' in line and not line.startswith('Nodes'):
                moves.append(line.split(':')[0].strip())
        return moves

    def get_best_move(self, fen: str, searchmoves: list[str] = None) -> tuple[str, int] | None:
        self.send_command(f'position fen {fen}')
        cmd = f'go depth {DEPTH}'
        if searchmoves:
            cmd += ' searchmoves ' + ' '.join(searchmoves)
        self.send_command(cmd)
        lines = self.read_until('bestmove')

        best_move = None
        for line in reversed(lines):
            if line.startswith('bestmove'):
                if '(none)' in line:
                    return None
                best_move = line.split()[1]
                break

        if not best_move:
            return None

        for line in reversed(lines):
            if line.startswith('info') and 'score' in line:
                parts = line.split()
                for i, part in enumerate(parts):
                    if part == 'score' and i + 2 < len(parts):
                        if parts[i + 1] == 'cp':
                            return (best_move, int(parts[i + 2]))
                        elif parts[i + 1] == 'mate':
                            mate = int(parts[i + 2])
                            return (best_move, (30001 - 2 * mate) if mate > 0 else (-30000 - 2 * mate))
        return None

    def shut_down(self):
        if self.process.poll() is None:
            self.send_command('quit')
            self.process.terminate()
            self.process.wait()

# Cell 5: Tree class
class Tree:
    """Manages the game tree structure for chess variant analysis.
    
    This class handles tree nodes (chess positions) and edges (moves between positions),
    storing them in NumPy arrays for efficient memory usage and fast access.
    """
    EDGE_DTYPE = np.dtype([('move', 'S5'), ('eval', '<i2'), ('child', '<i4')])

    def __init__(self):
        """Initialize the Tree with an engine and load existing data if available."""
        self.engine = Engine()
        self.node_fen = None
        self.node_offset = None
        self.node_num_edges = None
        self.node_all_moves = None
        self.node_refcount = None
        self.edges = None
        self.node_count = 0
        self.node_capacity = 0
        self.edge_count = 0
        self.edge_capacity = 0
        self.root_id = 0
        self.fen_to_id = {}
        self.free_list = []
        self.load_epd()

    def _grow_nodes(self, min_capacity):
        """Grow node arrays to accommodate more nodes.
        
        Uses efficient array pre-allocation instead of incremental resizing
        to reduce memory fragmentation and improve performance.
        
        Args:
            min_capacity: Minimum required capacity
        """
        new_capacity = max(min_capacity, self.node_capacity + 1_000_000)
        
        # Pre-allocate new arrays and copy old data - more efficient than resize
        new_node_fen = np.zeros(new_capacity, dtype='S28')
        new_node_fen[:self.node_count] = self.node_fen[:self.node_count]
        self.node_fen = new_node_fen
        
        new_node_offset = np.zeros(new_capacity, dtype=np.uint32)
        new_node_offset[:self.node_count] = self.node_offset[:self.node_count]
        self.node_offset = new_node_offset
        
        new_node_num_edges = np.zeros(new_capacity, dtype=np.uint8)
        new_node_num_edges[:self.node_count] = self.node_num_edges[:self.node_count]
        self.node_num_edges = new_node_num_edges
        
        new_node_all_moves = np.zeros(new_capacity, dtype=np.bool_)
        new_node_all_moves[:self.node_count] = self.node_all_moves[:self.node_count]
        self.node_all_moves = new_node_all_moves
        
        new_node_refcount = np.zeros(new_capacity, dtype=np.uint32)
        new_node_refcount[:self.node_count] = self.node_refcount[:self.node_count]
        self.node_refcount = new_node_refcount
        
        self.node_capacity = new_capacity

    def _grow_edges(self, min_capacity):
        """Grow edge array to accommodate more edges.
        
        Args:
            min_capacity: Minimum required capacity
        """
        new_capacity = max(min_capacity, self.edge_capacity + 2_000_000)
        new_edges = np.zeros(new_capacity, dtype=self.EDGE_DTYPE)
        new_edges[:self.edge_count] = self.edges[:self.edge_count]
        self.edges = new_edges
        self.edge_capacity = new_capacity

    def set_child(self, edge_index, new_child):
        """Update the child node ID for an edge, maintaining reference counts.
        
        Args:
            edge_index: Index of the edge in the edges array
            new_child: New child node ID to set
        """
        old_child = self.edges[edge_index]['child']
        if old_child == new_child:
            return
        if old_child >= 0 and self.node_refcount[old_child] > 0:
            self.node_refcount[old_child] -= 1
        if new_child >= 0:
            self.node_refcount[new_child] += 1
        self.edges[edge_index]['child'] = new_child

    def load_epd(self):
        """Load tree data from EPD file or create a new tree.
        
        The EPD format stores one node per line with format:
        node_id;fen;moves;evals;children;all_moves_flag
        
        Uses buffered reading for better performance with large files.
        """
        path = Path(EPD)
        if not path.exists():
            print('New tree')
            self.node_capacity, self.edge_capacity = 1_000_000, 2_000_000
            self.node_fen = np.zeros(self.node_capacity, dtype='S28')
            self.node_offset = np.zeros(self.node_capacity, dtype=np.uint32)
            self.node_num_edges = np.zeros(self.node_capacity, dtype=np.uint8)
            self.node_all_moves = np.zeros(self.node_capacity, dtype=np.bool_)
            self.node_refcount = np.zeros(self.node_capacity, dtype=np.uint32)
            self.edges = np.zeros(self.edge_capacity, dtype=self.EDGE_DTYPE)
            self.root_id, _ = self.create_node(self.engine.get_fen())
            return

        # Read last line to determine capacity needed
        with open(path, 'rb') as file:
            file.seek(0, 2)
            file_position = file.tell()
            while file_position > 0:
                file_position -= 1
                file.seek(file_position)
                if file.read(1) == b'\n' and file_position < file.seek(0, 2) - 1:
                    break
            last_line = file.readline().decode().strip()

        max_node_id = int(last_line.split(';')[0]) if last_line else 0
        self.node_capacity = max_node_id + 1 + 1_000_000
        self.edge_capacity = 2 * (max_node_id + 1) + 2_000_000

        # Pre-allocate all arrays
        self.node_fen = np.zeros(self.node_capacity, dtype='S28')
        self.node_offset = np.zeros(self.node_capacity, dtype=np.uint32)
        self.node_num_edges = np.zeros(self.node_capacity, dtype=np.uint8)
        self.node_all_moves = np.zeros(self.node_capacity, dtype=np.bool_)
        self.node_refcount = np.zeros(self.node_capacity, dtype=np.uint32)
        self.edges = np.zeros(self.edge_capacity, dtype=self.EDGE_DTYPE)

        # Read and parse file with buffering for better performance
        for line in path.read_text().splitlines():
            parts = line.strip().split(';')
            if len(parts) < 5:
                continue
            node_id, fen = int(parts[0]), parts[1]
            moves = parts[2].split(',') if parts[2] else []
            evaluations = [int(x) for x in parts[3].split(',')] if parts[3] else []
            children = [int(x) for x in parts[4].split(',')] if parts[4] else []
            all_moves = parts[5] == '1' if len(parts) > 5 else False

            self.node_fen[node_id] = fen.encode()
            self.node_offset[node_id] = self.edge_count
            self.node_num_edges[node_id] = len(moves)
            self.node_all_moves[node_id] = all_moves

            for i, (move, eval_score, child) in enumerate(zip(moves, evaluations, children)):
                self.edges[self.edge_count + i] = (move.encode(), eval_score, child)
                if child >= 0:
                    self.node_refcount[child] += 1
            self.edge_count += len(moves)
            self.fen_to_id[fen] = node_id
            self.node_count = max(self.node_count, node_id + 1)

        print(f'Loaded {self.node_count} nodes, {self.edge_count} edges')

    def save_epd(self):
        """Save tree data to EPD file, removing unreachable nodes.
        
        Performs garbage collection by identifying and removing nodes
        that are not reachable from the root. Uses buffered writing
        and atomic file replacement for safety and performance.
        """
        # Mark all reachable nodes using BFS
        reachable = np.zeros(self.node_count, dtype=np.bool_)
        reachable[self.root_id] = True
        queue = [self.root_id]
        while queue:
            node_id = queue.pop()
            offset, num_edges = self.node_offset[node_id], self.node_num_edges[node_id]
            for i in range(num_edges):
                child_id = self.edges[offset + i]['child']
                if child_id >= 0 and not reachable[child_id]:
                    reachable[child_id] = True
                    queue.append(child_id)

        # Update free list with unreachable nodes
        self.free_list = []
        for node_id in range(self.node_count):
            if not reachable[node_id] and node_id != self.root_id:
                self.free_list.append(node_id)
                fen = self.node_fen[node_id].decode()
                if fen in self.fen_to_id:
                    del self.fen_to_id[fen]

        # Write to temporary file with buffering, then atomically replace
        temp_path = Path(EPD + '.tmp')
        with open(temp_path, 'w', buffering=8192 * 16) as file:  # 128KB buffer for better performance
            for i, node_id in enumerate(np.nonzero(reachable)[0]):
                fen = self.node_fen[node_id].decode()
                offset, num_edges = self.node_offset[node_id], self.node_num_edges[node_id]
                all_moves_flag = '1' if self.node_all_moves[node_id] else '0'
                moves = ','.join(self.edges[offset + j]['move'].decode() for j in range(num_edges))
                evaluations = ','.join(str(self.edges[offset + j]['eval']) for j in range(num_edges))
                children = ','.join(str(self.edges[offset + j]['child']) for j in range(num_edges))
                file.write(f'{node_id};{fen};{moves};{evaluations};{children};{all_moves_flag};\n')
                # Flush periodically to avoid excessive memory usage
                if i % 1000000 == 0:
                    file.flush()
        
        # Atomic replacement - ensures file integrity even if process is interrupted
        os.replace(temp_path, Path(EPD))

        # Collect statistics
        stats = {'unexpanded': 0, 'solved': 0}
        for node_id in np.nonzero(reachable)[0]:
            offset, num_edges = self.node_offset[node_id], self.node_num_edges[node_id]
            for idx in range(num_edges):
                child_id = self.edges[offset + idx]['child']
                if child_id == -1:
                    stats['unexpanded'] += 1
                elif child_id == -2:
                    stats['solved'] += 1

        print(f"Saved {reachable.sum()} nodes | unexpanded={stats['unexpanded']} solved={stats['solved']}")

    def create_node(self, fen):
        """Create a new node for the given FEN position.
        
        Args:
            fen: FEN string representing the chess position
            
        Returns:
            tuple: (node_id, mate_evaluation) where mate_evaluation is None if not a mate position
        """
        result = self.engine.get_best_move(fen)
        if result is None or abs(result[1]) > 29000:
            return (None, result[1] if result else 29999)

        best_move, best_eval = result
        legal_moves = self.engine.get_perft_moves(fen)

        # Reuse node ID from free list or create new one
        if self.free_list:
            node_id = self.free_list.pop()
        else:
            node_id = self.node_count
            self.node_count += 1
            if self.node_count >= self.node_capacity:
                self._grow_nodes(self.node_count + 1)
        if self.edge_count + 1 >= self.edge_capacity:
            self._grow_edges(self.edge_count + 1)

        self.node_fen[node_id] = fen.encode()
        self.node_offset[node_id] = self.edge_count
        self.node_num_edges[node_id] = 1
        self.node_all_moves[node_id] = len(legal_moves) == 1
        self.node_refcount[node_id] = 0

        self.edges[self.edge_count] = (best_move.encode(), best_eval, -1)
        self.edge_count += 1
        self.fen_to_id[fen] = node_id
        return (node_id, None)

    def add_edge(self, node_id, move, evaluation, child_id):
        """Add a new edge (move) to an existing node.
        
        Args:
            node_id: ID of the parent node
            move: UCI move string
            evaluation: Centipawn evaluation of the move
            child_id: ID of the child node (-1 for unexpanded, -2 for terminal)
        """
        if self.edge_count >= self.edge_capacity:
            self._grow_edges(self.edge_count + 1)

        old_offset = int(self.node_offset[node_id])
        old_num_edges = int(self.node_num_edges[node_id])
        
        # If edges are not at the end, relocate them to maintain contiguity
        if old_offset + old_num_edges < self.edge_count:
            new_offset = self.edge_count
            self.edges[new_offset:new_offset + old_num_edges] = self.edges[old_offset:old_offset + old_num_edges]
            self.node_offset[node_id] = new_offset
            self.edge_count = new_offset + old_num_edges

        self.edges[self.edge_count] = (move.encode(), evaluation, child_id)
        self.edge_count += 1
        self.node_num_edges[node_id] += 1

    def add_alternative(self, node_id):
        """Add an alternative move to a node that hasn't been fully explored.
        
        Args:
            node_id: ID of the node to add an alternative move to
            
        Returns:
            bool: True if an alternative was added, False if all moves already explored
        """
        if self.node_all_moves[node_id]:
            return False

        fen = self.node_fen[node_id].decode()
        legal_moves = self.engine.get_perft_moves(fen)
        offset, num_edges = self.node_offset[node_id], self.node_num_edges[node_id]
        existing_moves = {self.edges[offset + i]['move'].decode() for i in range(num_edges)}
        needed_moves = [move for move in legal_moves if move not in existing_moves]

        if not needed_moves:
            self.node_all_moves[node_id] = True
            return False

        result = self.engine.get_best_move(fen, needed_moves)
        if result is None:
            self.node_all_moves[node_id] = True
            return False

        move, evaluation = result
        self.add_edge(node_id, move, evaluation, -2 if abs(evaluation) > 29000 else -1)
        if self.node_num_edges[node_id] == len(legal_moves):
            self.node_all_moves[node_id] = True
        return True

    def expand_move(self, node_id, edge_index):
        """Expand an unexpanded edge by creating or finding the child node.
        
        Args:
            node_id: ID of the parent node
            edge_index: Index of the edge to expand (relative to node's offset)
            
        Returns:
            int or None: Child node ID if successful, None if terminal position
        """
        offset = self.node_offset[node_id]
        child_id = self.edges[offset + edge_index]['child']

        # Already expanded
        if child_id >= 0:
            return child_id
        # Terminal (mate) position
        if child_id == -2:
            return None

        fen = self.node_fen[node_id].decode()
        move = self.edges[offset + edge_index]['move'].decode()
        child_fen = self.engine.get_fen(f'position fen {fen} moves {move}')

        # Check if position already exists (transposition)
        if child_fen in self.fen_to_id:
            child_id = self.fen_to_id[child_fen]
            self.set_child(offset + edge_index, child_id)
            return child_id

        # Create new node
        child_id, mate_evaluation = self.create_node(child_fen)
        if child_id is None:
            self.set_child(offset + edge_index, -2)
            # Apply negamax to mate evaluation
            negamax_eval = -mate_evaluation
            if negamax_eval > 0:
                negamax_eval -= 1
            elif negamax_eval < 0:
                negamax_eval += 1
            self.edges[offset + edge_index]['eval'] = negamax_eval
            return None

        self.set_child(offset + edge_index, child_id)
        return child_id

    def backprop_node(self, node_id):
        """Backpropagate evaluations from child nodes to parent node.
        
        Updates edge evaluations based on child node's best evaluation
        using negamax algorithm. Marks terminal positions.
        
        Args:
            node_id: ID of the node to backpropagate
        """
        offset, num_edges = self.node_offset[node_id], self.node_num_edges[node_id]
        if num_edges == 0:
            return

        for i in range(num_edges):
            child_id = self.edges[offset + i]['child']
            if child_id < 0:
                continue

            child_offset, child_num_edges = self.node_offset[child_id], self.node_num_edges[child_id]
            if child_num_edges == 0:
                continue

            # Get best evaluation from child node
            child_best_eval = self.edges[child_offset:child_offset + child_num_edges]['eval'].max()
            
            # Apply negamax transformation
            negamax_eval = -child_best_eval
            if negamax_eval > 0:
                negamax_eval -= 1
            elif negamax_eval < 0:
                negamax_eval += 1

            self.edges[offset + i]['eval'] = negamax_eval
            # Mark as terminal if mate score
            if abs(negamax_eval) > 29000:
                self.set_child(offset + i, -2)

    def shift_eval_to_zero(self, node_id, edge_index):
        """Shift evaluation towards zero by one centipawn (for exploration).
        
        Args:
            node_id: ID of the parent node
            edge_index: Index of the edge to shift
            
        Returns:
            bool: True if evaluation is now in range [-1, 1], False otherwise
        """
        offset = self.node_offset[node_id]
        evaluation = self.edges[offset + edge_index]['eval']
        if evaluation > 0:
            self.edges[offset + edge_index]['eval'] = evaluation - 1
        elif evaluation < 0:
            self.edges[offset + edge_index]['eval'] = evaluation + 1
        return evaluation in (-1, 0, 1)

    def is_node_forced(self, node_id):
        """Check if a node has only one non-losing move.
        
        Args:
            node_id: ID of the node to check
            
        Returns:
            bool: True if node is forced (only one viable move), False otherwise
        """
        if not self.node_all_moves[node_id]:
            return False
        offset, num_edges = self.node_offset[node_id], self.node_num_edges[node_id]
        non_losing_count = 0
        for i in range(num_edges):
            child_id, evaluation = self.edges[offset + i]['child'], self.edges[offset + i]['eval']
            # Skip losing moves
            if child_id == -2 and evaluation < -29000:
                continue
            non_losing_count += 1
            if non_losing_count > 1:
                return False
        return non_losing_count == 1

    def check_forced_loop(self, path, loop_start):
        """Check and mark forced loops (repetitions with no choice).
        
        Args:
            path: List of (node_id, edge_index) tuples representing current path
            loop_start: Index in path where the loop begins
            
        Returns:
            bool: True if a forced loop was detected and marked, False otherwise
        """
        if len(path) - loop_start < 4:
            return False

        # Verify all moves in loop are forced
        for i in range(loop_start, len(path)):
            if not self.is_node_forced(path[i][0]):
                return False

        # Mark all edges in the loop as draws (evaluation 0)
        for i in range(loop_start, len(path)):
            node_id, edge_index = path[i]
            offset = self.node_offset[node_id]
            self.set_child(offset + edge_index, -2)
            self.edges[offset + edge_index]['eval'] = 0

        # Propagate draw backwards through forced moves
        for i in range(loop_start - 1, -1, -1):
            node_id, edge_index = path[i]
            if not self.is_node_forced(node_id):
                offset = self.node_offset[node_id]
                self.set_child(offset + edge_index, -2)
                self.edges[offset + edge_index]['eval'] = 0
                break
            offset = self.node_offset[node_id]
            self.set_child(offset + edge_index, -2)
            self.edges[offset + edge_index]['eval'] = 0

        return True

    def path_to_game(self, path, suffix=''):
        """Convert a path through the tree to a game notation string.
        
        Args:
            path: List of (node_id, edge_index) tuples
            suffix: Optional suffix to append (e.g., "MATE", "LOOP")
            
        Returns:
            str: Game notation with move numbers and evaluations
        """
        parts = []
        for i, (node_id, edge_index) in enumerate(path):
            offset = self.node_offset[node_id]
            move = self.edges[offset + edge_index]['move'].decode()
            evaluation = self.edges[offset + edge_index]['eval']
            if i % 2 == 0:
                parts.append(f"{i // 2 + 1}.")
            parts.append(f"{move} {evaluation:+d}")
        if suffix:
            parts.append(suffix)
        return ' '.join(parts)

    def yoyo(self):
        """Main tree exploration algorithm using yo-yo traversal.
        
        Explores the game tree by moving forward along best moves and backward
        to explore alternatives. Handles loops, mate positions, and saves progress
        periodically. The algorithm balances exploration and exploitation.
        """
        path = []
        zero_visited = set()
        node_id = self.root_id
        direction = 'FORWARD'
        game_count = 0

        def end_game(suffix):
            """End current game exploration and prepare for backtracking."""
            nonlocal game_count, direction
            game_count += 1
            if game_count % 1024 == 0:
                print(f"[{game_count}] {self.path_to_game(path, suffix)}")
            if game_count % 65536 == 0:
                # Periodic backpropagation and saving
                for node_id, _ in reversed(path):
                    self.backprop_node(node_id)
                self.save_epd()
                shutil.copy(f'/content/{EPD}', f'{DIR}{EPD}')
                path.clear()
            zero_visited.clear()
            direction = 'BACKWARD'

        try:
            while True:
                offset, num_edges = self.node_offset[node_id], self.node_num_edges[node_id]
                if num_edges == 0:
                    break

                self.backprop_node(node_id)
                evaluations = self.edges[offset:offset + num_edges]['eval'].astype(np.int32)
                children = self.edges[offset:offset + num_edges]['child'].astype(np.int32)

                if direction == 'FORWARD':
                    # Filter out terminal positions
                    valid_mask = children != -2
                    if not np.any(valid_mask):
                        best_edge_index = int(np.argmax(evaluations))
                        path.append((node_id, best_edge_index))
                        best_evaluation = evaluations[best_edge_index]
                        end_game("MATE")
                        continue

                    # Choose best non-terminal move
                    scores = np.where(valid_mask, evaluations, -30000)
                    edge_index = int(np.argmax(scores))

                    # Check for loops
                    if (node_id, edge_index) in zero_visited:
                        path.append((node_id, edge_index))
                        loop_start = next(i for i, (nid, eidx) in enumerate(path)
                                          if nid == node_id and eidx == edge_index)
                        self.check_forced_loop(path, loop_start)
                        end_game("LOOP")
                        continue

                    # Shift evaluation towards zero for exploration
                    if self.shift_eval_to_zero(node_id, edge_index):
                        zero_visited.add((node_id, edge_index))

                    # Try to add alternative moves
                    if not self.node_all_moves[node_id]:
                        self.add_alternative(node_id)
                        offset = self.node_offset[node_id]

                    # Expand the move if needed
                    child_id = children[edge_index]
                    if child_id == -1:
                        child_id = self.expand_move(node_id, edge_index)
                        if child_id is None:
                            path.append((node_id, edge_index))
                            evaluation = self.edges[offset + edge_index]['eval']
                            end_game("MATE")
                            continue

                    path.append((node_id, edge_index))
                    node_id = child_id

                else:  # BACKWARD direction
                    if not path:
                        node_id = self.root_id
                        direction = 'FORWARD'
                        continue

                    parent_id, used_edge_index = path.pop()
                    zero_visited.discard((parent_id, used_edge_index))
                    parent_offset, parent_num_edges = self.node_offset[parent_id], self.node_num_edges[parent_id]
                    self.backprop_node(parent_id)

                    parent_evaluations = self.edges[parent_offset:parent_offset + parent_num_edges]['eval'].astype(np.int32)
                    parent_children = self.edges[parent_offset:parent_offset + parent_num_edges]['child'].astype(np.int32)

                    # Give credit to unexplored alternatives
                    credit_mask = (parent_children != -2)
                    credit_mask[used_edge_index] = False
                    self.edges[parent_offset:parent_offset + parent_num_edges]['eval'] += credit_mask.astype(np.int16)

                    parent_evaluations = self.edges[parent_offset:parent_offset + parent_num_edges]['eval'].astype(np.int32)
                    used_edge_evaluation = parent_evaluations[used_edge_index]

                    # Find best alternative move
                    best_alt_index, alt_edge_evaluation = -1, -30000
                    for i in range(parent_num_edges):
                        if i != used_edge_index and parent_evaluations[i] > alt_edge_evaluation:
                            alt_edge_evaluation, best_alt_index = parent_evaluations[i], i

                    # Try to add more alternatives if needed
                    if not self.node_all_moves[parent_id] and best_alt_index == -1:
                        if self.add_alternative(parent_id):
                            parent_offset, parent_num_edges = self.node_offset[parent_id], self.node_num_edges[parent_id]
                            if self.edges[parent_offset + parent_num_edges - 1]['child'] != -2:
                                best_alt_index = parent_num_edges - 1
                                alt_edge_evaluation = self.edges[parent_offset + parent_num_edges - 1]['eval']

                    # Switch to alternative if it's significantly better
                    if best_alt_index >= 0 and alt_edge_evaluation > used_edge_evaluation + 64 * len(path):
                        self.shift_eval_to_zero(parent_id, best_alt_index)

                        child_id = self.edges[parent_offset + best_alt_index]['child']
                        if child_id == -1:
                            child_id = self.expand_move(parent_id, best_alt_index)

                        if child_id is not None and child_id >= 0:
                            path.append((parent_id, best_alt_index))
                            node_id = child_id
                            direction = 'FORWARD'
                            continue

                    node_id = parent_id

        except KeyboardInterrupt:
            print('\nInterrupted')
        finally:
            # Final cleanup and save
            for node_id, _ in reversed(path):
                self.backprop_node(node_id)
            self.save_epd()
            shutil.copy(f'/content/{EPD}', f'{DIR}{EPD}')
            self.engine.shut_down()

# Cell 7: Run
tree = Tree()
tree.yoyo()