# -*- coding: utf-8 -*-
"""YoYo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17L7BiRBbwJXNmjGZXJ7Hay4iRN_UPke7
"""

# Cell 1: Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# Cell 2: Compile Fairy Stockfish
import os

fairy_path = "/content/drive/MyDrive/trees/fairy_stockfish"

if os.path.exists(fairy_path):
    print("Fairy Stockfish exists")
else:
    print("Compiling Fairy Stockfish...")
    !git clone https://github.com/fairy-stockfish/Fairy-Stockfish.git /content/Fairy-Stockfish
    !cd /content/Fairy-Stockfish/src && make build ARCH=x86-64-modern all=yes -j4
    !mkdir -p /content/drive/MyDrive/trees
    !cp /content/Fairy-Stockfish/src/stockfish {fairy_path}
    !chmod +x {fairy_path}
    print(f"Done: {fairy_path}")

# Cell 3: Setup
import os, shutil
from pathlib import Path
import numpy as np
import time

ENGINE       = '/content/fairy_stockfish'
VARIANT      = 'tinyhouse'  #@param ['chess', 'atomic', 'tinyhouse']
THREADS      = 2            #@param {type:'integer'}
HASHMB       = 4096         #@param {type:'integer'}
DEPTH        = 5            #@param {type:'integer'}

DRIVE_DIR = '/content/drive/MyDrive/trees'
DIR = f'{DRIVE_DIR}/{VARIANT}/'
os.makedirs(DIR, exist_ok=True)

EPD = f'{VARIANT}_yoyo.epd'

shutil.copy(f'{DRIVE_DIR}/fairy_stockfish', ENGINE)
os.chmod(ENGINE, 0o755)

INI = None
if os.path.exists(f'{DRIVE_DIR}/variants.ini'):
    shutil.copy(f'{DRIVE_DIR}/variants.ini', '/content/variants.ini')
    INI = '/content/variants.ini'

NNUE = None
for file in Path(DIR).glob('*.nnue'):
    shutil.copy(file, '/content/')
    NNUE = f'/content/{file.name}'
    break

if os.path.exists(f'{DIR}{EPD}'):
    shutil.copy(f'{DIR}{EPD}', f'/content/{EPD}')

print(f"Engine: {ENGINE}")
print(f"Variant: {VARIANT}")
print(f"NNUE: {NNUE or 'None'}")

# Cell 4: Engine class
import subprocess

class Engine:
    def __init__(self):
        self.process = subprocess.Popen(
            [ENGINE],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            bufsize=0
        )
        self.send_command('uci')
        self.read_until('uciok')

        if INI:
            self.send_command(f'load {INI}')
        self.send_command(f'setoption name UCI_Variant value {VARIANT}')

        if NNUE:
            self.send_command(f'setoption name EvalFile value {NNUE}')
            self.send_command('setoption name Use NNUE value true')

        self.send_command(f'setoption name Threads value {THREADS}')
        self.send_command(f'setoption name Hash value {HASHMB}')

    def send_command(self, command: str):
        if self.process.poll() is None:
            self.process.stdin.write(f'{command}\n')
            self.process.stdin.flush()

    def read_until(self, terminator: str) -> list[str]:
        lines = []
        while True:
            line = self.process.stdout.readline().strip()
            if not line and self.process.poll() is not None:
                break
            lines.append(line)
            if terminator in line:
                break
        return lines

    def get_fen(self, position_cmd: str = 'position startpos') -> str:
        self.send_command(position_cmd)
        self.send_command('d')
        for line in self.read_until('Fen:'):
            if 'Fen:' in line:
                return ' '.join(line.split()[1:3])
        raise RuntimeError(f'Failed to get FEN')

    def get_perft_moves(self, fen: str) -> list[str]:
        self.send_command(f'position fen {fen}')
        self.send_command('go perft 1')
        lines = self.read_until('Nodes searched:')
        moves = []
        for line in lines:
            if ':' in line and not line.startswith('Nodes'):
                moves.append(line.split(':')[0].strip())
        return moves

    def get_best_move(self, fen: str, searchmoves: list[str] = None) -> tuple[str, int] | None:
        self.send_command(f'position fen {fen}')
        cmd = f'go depth {DEPTH}'
        if searchmoves:
            cmd += ' searchmoves ' + ' '.join(searchmoves)
        self.send_command(cmd)
        lines = self.read_until('bestmove')

        best_move = None
        for line in reversed(lines):
            if line.startswith('bestmove'):
                if '(none)' in line:
                    return None
                best_move = line.split()[1]
                break

        if not best_move:
            return None

        for line in reversed(lines):
            if line.startswith('info') and 'score' in line:
                parts = line.split()
                for i, part in enumerate(parts):
                    if part == 'score' and i + 2 < len(parts):
                        if parts[i + 1] == 'cp':
                            return (best_move, int(parts[i + 2]))
                        elif parts[i + 1] == 'mate':
                            mate = int(parts[i + 2])
                            return (best_move, (30001 - 2 * mate) if mate > 0 else (-30000 - 2 * mate))
        return None

    def shut_down(self):
        if self.process.poll() is None:
            self.send_command('quit')
            self.process.terminate()
            self.process.wait()

# Cell 5: Tree class
class Tree:
    EDGE_DTYPE = np.dtype([('move', 'S5'), ('eval', '<i2'), ('child', '<i4')])

    def __init__(self):
        self.engine = Engine()
        self.node_fen = None
        self.node_offset = None
        self.node_num_edges = None
        self.node_all_moves = None
        self.node_refcount = None
        self.edges = None
        self.node_count = 0
        self.node_capacity = 0
        self.edge_count = 0
        self.edge_capacity = 0
        self.root_id = 0
        self.fen_to_id = {}
        self.free_list = []
        self.load_epd()

    def _grow_nodes(self, min_cap):
        new_cap = max(min_cap, self.node_capacity + 1_000_000)
        self.node_fen = np.resize(self.node_fen, new_cap)
        self.node_offset = np.resize(self.node_offset, new_cap)
        self.node_num_edges = np.resize(self.node_num_edges, new_cap)
        self.node_all_moves = np.resize(self.node_all_moves, new_cap)
        self.node_refcount = np.resize(self.node_refcount, new_cap)
        self.node_capacity = new_cap

    def _grow_edges(self, min_cap):
        new_cap = max(min_cap, self.edge_capacity + 2_000_000)
        new_edges = np.zeros(new_cap, dtype=self.EDGE_DTYPE)
        new_edges[:self.edge_count] = self.edges[:self.edge_count]
        self.edges = new_edges
        self.edge_capacity = new_cap

    def set_child(self, edge_idx, new_child):
        old_child = self.edges[edge_idx]['child']
        if old_child == new_child:
            return
        if old_child >= 0 and self.node_refcount[old_child] > 0:
            self.node_refcount[old_child] -= 1
        if new_child >= 0:
            self.node_refcount[new_child] += 1
        self.edges[edge_idx]['child'] = new_child

    def load_epd(self):
        path = Path(EPD)
        if not path.exists():
            print('New tree')
            self.node_capacity, self.edge_capacity = 1_000_000, 2_000_000
            self.node_fen = np.zeros(self.node_capacity, dtype='S28')
            self.node_offset = np.zeros(self.node_capacity, dtype=np.uint32)
            self.node_num_edges = np.zeros(self.node_capacity, dtype=np.uint8)
            self.node_all_moves = np.zeros(self.node_capacity, dtype=np.bool_)
            self.node_refcount = np.zeros(self.node_capacity, dtype=np.uint32)
            self.edges = np.zeros(self.edge_capacity, dtype=self.EDGE_DTYPE)
            self.root_id, _ = self.create_node(self.engine.get_fen())
            return

        with open(path, 'rb') as f:
            f.seek(0, 2)
            pos = f.tell()
            while pos > 0:
                pos -= 1
                f.seek(pos)
                if f.read(1) == b'\n' and pos < f.seek(0, 2) - 1:
                    break
            last_line = f.readline().decode().strip()

        max_node_id = int(last_line.split(';')[0]) if last_line else 0
        self.node_capacity = max_node_id + 1 + 1_000_000
        self.edge_capacity = 2 * (max_node_id + 1) + 2_000_000

        self.node_fen = np.zeros(self.node_capacity, dtype='S28')
        self.node_offset = np.zeros(self.node_capacity, dtype=np.uint32)
        self.node_num_edges = np.zeros(self.node_capacity, dtype=np.uint8)
        self.node_all_moves = np.zeros(self.node_capacity, dtype=np.bool_)
        self.node_refcount = np.zeros(self.node_capacity, dtype=np.uint32)
        self.edges = np.zeros(self.edge_capacity, dtype=self.EDGE_DTYPE)

        for line in path.read_text().splitlines():
            parts = line.strip().split(';')
            if len(parts) < 5:
                continue
            node_id, fen = int(parts[0]), parts[1]
            moves = parts[2].split(',') if parts[2] else []
            evals = [int(x) for x in parts[3].split(',')] if parts[3] else []
            children = [int(x) for x in parts[4].split(',')] if parts[4] else []
            all_moves = parts[5] == '1' if len(parts) > 5 else False

            self.node_fen[node_id] = fen.encode()
            self.node_offset[node_id] = self.edge_count
            self.node_num_edges[node_id] = len(moves)
            self.node_all_moves[node_id] = all_moves

            for i, (m, e, c) in enumerate(zip(moves, evals, children)):
                self.edges[self.edge_count + i] = (m.encode(), e, c)
                if c >= 0:
                    self.node_refcount[c] += 1
            self.edge_count += len(moves)
            self.fen_to_id[fen] = node_id
            self.node_count = max(self.node_count, node_id + 1)

        print(f'Loaded {self.node_count} nodes, {self.edge_count} edges')

    def save_epd(self):
        reachable = np.zeros(self.node_count, dtype=np.bool_)
        reachable[self.root_id] = True
        queue = [self.root_id]
        while queue:
            nid = queue.pop()
            off, n = self.node_offset[nid], self.node_num_edges[nid]
            for i in range(n):
                cid = self.edges[off + i]['child']
                if cid >= 0 and not reachable[cid]:
                    reachable[cid] = True
                    queue.append(cid)

        self.free_list = []
        for nid in range(self.node_count):
            if not reachable[nid] and nid != self.root_id:
                self.free_list.append(nid)
                fen = self.node_fen[nid].decode()
                if fen in self.fen_to_id:
                    del self.fen_to_id[fen]

        with open(Path(EPD + '.tmp'), 'w') as f:
            for i, node_id in enumerate(np.nonzero(reachable)[0]):
                fen = self.node_fen[node_id].decode()
                off, n = self.node_offset[node_id], self.node_num_edges[node_id]
                all_m = '1' if self.node_all_moves[node_id] else '0'
                moves = ','.join(self.edges[off + j]['move'].decode() for j in range(n))
                evals = ','.join(str(self.edges[off + j]['eval']) for j in range(n))
                children = ','.join(str(self.edges[off + j]['child']) for j in range(n))
                f.write(f'{node_id};{fen};{moves};{evals};{children};{all_m};\n')
                if i % 1000000 == 0:
                    f.flush()
        os.replace(Path(EPD + '.tmp'), Path(EPD))

        stats = {'unexpanded': 0, 'solved': 0}
        for nid in np.nonzero(reachable)[0]:
            offset, num_edges = self.node_offset[nid], self.node_num_edges[nid]
            for idx in range(num_edges):
                child_id = self.edges[offset + idx]['child']
                if child_id == -1:
                    stats['unexpanded'] += 1
                elif child_id == -2:
                    stats['solved'] += 1

        print(f"Saved {reachable.sum()} nodes | unexpanded={stats['unexpanded']} solved={stats['solved']}")

    def create_node(self, fen):
        result = self.engine.get_best_move(fen)
        if result is None or abs(result[1]) > 29000:
            return (None, result[1] if result else 29999)

        best_move, best_eval = result
        legal = self.engine.get_perft_moves(fen)

        if self.free_list:
            node_id = self.free_list.pop()
        else:
            node_id = self.node_count
            self.node_count += 1
            if self.node_count >= self.node_capacity:
                self._grow_nodes(self.node_count + 1)
        if self.edge_count + 1 >= self.edge_capacity:
            self._grow_edges(self.edge_count + 1)

        self.node_fen[node_id] = fen.encode()
        self.node_offset[node_id] = self.edge_count
        self.node_num_edges[node_id] = 1
        self.node_all_moves[node_id] = len(legal) == 1
        self.node_refcount[node_id] = 0

        self.edges[self.edge_count] = (best_move.encode(), best_eval, -1)
        self.edge_count += 1
        self.fen_to_id[fen] = node_id
        return (node_id, None)

    def add_edge(self, node_id, move, ev, child):
        if self.edge_count >= self.edge_capacity:
            self._grow_edges(self.edge_count + 1)

        old_off = int(self.node_offset[node_id])
        old_num = int(self.node_num_edges[node_id])
        if old_off + old_num < self.edge_count:
            new_off = self.edge_count
            self.edges[new_off:new_off + old_num] = self.edges[old_off:old_off + old_num]
            self.node_offset[node_id] = new_off
            self.edge_count = new_off + old_num

        self.edges[self.edge_count] = (move.encode(), ev, child)
        self.edge_count += 1
        self.node_num_edges[node_id] += 1

    def add_alternative(self, node_id):
        if self.node_all_moves[node_id]:
            return False

        fen = self.node_fen[node_id].decode()
        legal = self.engine.get_perft_moves(fen)
        off, n = self.node_offset[node_id], self.node_num_edges[node_id]
        have = {self.edges[off + i]['move'].decode() for i in range(n)}
        need = [m for m in legal if m not in have]

        if not need:
            self.node_all_moves[node_id] = True
            return False

        result = self.engine.get_best_move(fen, need)
        if result is None:
            self.node_all_moves[node_id] = True
            return False

        move, ev = result
        self.add_edge(node_id, move, ev, -2 if abs(ev) > 29000 else -1)
        if self.node_num_edges[node_id] == len(legal):
            self.node_all_moves[node_id] = True
        return True

    def expand_move(self, node_id, edge_idx):
        off = self.node_offset[node_id]
        child_id = self.edges[off + edge_idx]['child']

        if child_id >= 0:
            return child_id
        if child_id == -2:
            return None

        fen = self.node_fen[node_id].decode()
        move = self.edges[off + edge_idx]['move'].decode()
        child_fen = self.engine.get_fen(f'position fen {fen} moves {move}')

        if child_fen in self.fen_to_id:
            child_id = self.fen_to_id[child_fen]
            self.set_child(off + edge_idx, child_id)
            return child_id

        child_id, mate_eval = self.create_node(child_fen)
        if child_id is None:
            self.set_child(off + edge_idx, -2)
            negamax = -mate_eval
            if negamax > 0:
                negamax -= 1
            elif negamax < 0:
                negamax += 1
            self.edges[off + edge_idx]['eval'] = negamax
            return None

        self.set_child(off + edge_idx, child_id)
        return child_id

    def backprop_node(self, node_id):
        off, n = self.node_offset[node_id], self.node_num_edges[node_id]
        if n == 0:
            return

        for i in range(n):
            child_id = self.edges[off + i]['child']
            if child_id < 0:
                continue

            child_off, child_n = self.node_offset[child_id], self.node_num_edges[child_id]
            if child_n == 0:
                continue

            child_best = self.edges[child_off:child_off + child_n]['eval'].max()
            negamax = -child_best
            if negamax > 0:
                negamax -= 1
            elif negamax < 0:
                negamax += 1

            self.edges[off + i]['eval'] = negamax
            if abs(negamax) > 29000:
                self.set_child(off + i, -2)

    def shift_eval_to_zero(self, node_id, edge_idx):
        off = self.node_offset[node_id]
        ev = self.edges[off + edge_idx]['eval']
        if ev > 0:
            self.edges[off + edge_idx]['eval'] = ev - 1
        elif ev < 0:
            self.edges[off + edge_idx]['eval'] = ev + 1
        return ev in (-1, 0, 1)

    def is_node_forced(self, node_id):
        if not self.node_all_moves[node_id]:
            return False
        off, n = self.node_offset[node_id], self.node_num_edges[node_id]
        non_losing = 0
        for i in range(n):
            child, ev = self.edges[off + i]['child'], self.edges[off + i]['eval']
            if child == -2 and ev < -29000:
                continue
            non_losing += 1
            if non_losing > 1:
                return False
        return non_losing == 1

    def check_forced_loop(self, path, loop_start):
        if len(path) - loop_start < 4:
            return False

        for i in range(loop_start, len(path)):
            if not self.is_node_forced(path[i][0]):
                return False

        for i in range(loop_start, len(path)):
            nid, eidx = path[i]
            off = self.node_offset[nid]
            self.set_child(off + eidx, -2)
            self.edges[off + eidx]['eval'] = 0

        for i in range(loop_start - 1, -1, -1):
            nid, eidx = path[i]
            if not self.is_node_forced(nid):
                off = self.node_offset[nid]
                self.set_child(off + eidx, -2)
                self.edges[off + eidx]['eval'] = 0
                break
            off = self.node_offset[nid]
            self.set_child(off + eidx, -2)
            self.edges[off + eidx]['eval'] = 0

        return True

    def path_to_game(self, path, suffix=''):
        parts = []
        for i, (nid, eidx) in enumerate(path):
            off = self.node_offset[nid]
            move = self.edges[off + eidx]['move'].decode()
            ev = self.edges[off + eidx]['eval']
            if i % 2 == 0:
                parts.append(f"{i // 2 + 1}.")
            parts.append(f"{move} {ev:+d}")
        if suffix:
            parts.append(suffix)
        return ' '.join(parts)

    def yoyo(self):
        path = []
        zero_visited = set()
        node_id = self.root_id
        direction = 'FORWARD'
        game = 0

        def end_game(suffix):
            nonlocal game, direction
            game += 1
            if game % 1024 == 0:
                print(f"[{game}] {self.path_to_game(path, suffix)}")
            if game % 65536 == 0:
                for nid, _ in reversed(path):
                    self.backprop_node(nid)
                self.save_epd()
                shutil.copy(f'/content/{EPD}', f'{DIR}{EPD}')
                path.clear()
            zero_visited.clear()
            direction = 'BACKWARD'

        try:
            while True:
                off, n = self.node_offset[node_id], self.node_num_edges[node_id]
                if n == 0:
                    break

                self.backprop_node(node_id)
                evals = self.edges[off:off + n]['eval'].astype(np.int32)
                children = self.edges[off:off + n]['child'].astype(np.int32)

                if direction == 'FORWARD':
                    valid_mask = children != -2
                    if not np.any(valid_mask):
                        best_idx = int(np.argmax(evals))
                        path.append((node_id, best_idx))
                        best_eval = evals[best_idx]
                        end_game("MATE")
                        continue

                    scores = np.where(valid_mask, evals, -30000)
                    edge_idx = int(np.argmax(scores))

                    if (node_id, edge_idx) in zero_visited:
                        path.append((node_id, edge_idx))
                        loop_start = next(i for i, (nid, eidx) in enumerate(path)
                                          if nid == node_id and eidx == edge_idx)
                        self.check_forced_loop(path, loop_start)
                        end_game("LOOP")
                        continue

                    if self.shift_eval_to_zero(node_id, edge_idx):
                        zero_visited.add((node_id, edge_idx))

                    if not self.node_all_moves[node_id]:
                        self.add_alternative(node_id)
                        off = self.node_offset[node_id]

                    child_id = children[edge_idx]
                    if child_id == -1:
                        child_id = self.expand_move(node_id, edge_idx)
                        if child_id is None:
                            path.append((node_id, edge_idx))
                            ev = self.edges[off + edge_idx]['eval']
                            end_game("MATE")
                            continue

                    path.append((node_id, edge_idx))
                    node_id = child_id

                else:
                    if not path:
                        node_id = self.root_id
                        direction = 'FORWARD'
                        continue

                    parent_id, used_idx = path.pop()
                    zero_visited.discard((parent_id, used_idx))
                    p_off, p_n = self.node_offset[parent_id], self.node_num_edges[parent_id]
                    self.backprop_node(parent_id)

                    p_evals = self.edges[p_off:p_off + p_n]['eval'].astype(np.int32)
                    p_children = self.edges[p_off:p_off + p_n]['child'].astype(np.int32)

                    credit_mask = (p_children != -2)
                    credit_mask[used_idx] = False
                    self.edges[p_off:p_off + p_n]['eval'] += credit_mask.astype(np.int16)

                    p_evals = self.edges[p_off:p_off + p_n]['eval'].astype(np.int32)
                    used_edge_eval = p_evals[used_idx]

                    best_alt_idx, alt_edge_eval = -1, -30000
                    for i in range(p_n):
                        if i != used_idx and p_evals[i] > alt_edge_eval:
                            alt_edge_eval, best_alt_idx = p_evals[i], i

                    if not self.node_all_moves[parent_id] and best_alt_idx == -1:
                        if self.add_alternative(parent_id):
                            p_off, p_n = self.node_offset[parent_id], self.node_num_edges[parent_id]
                            if self.edges[p_off + p_n - 1]['child'] != -2:
                                best_alt_idx = p_n - 1
                                alt_edge_eval = self.edges[p_off + p_n - 1]['eval']

                    if best_alt_idx >= 0 and alt_edge_eval > used_edge_eval + 64 * len(path):
                        self.shift_eval_to_zero(parent_id, best_alt_idx)

                        child_id = self.edges[p_off + best_alt_idx]['child']
                        if child_id == -1:
                            child_id = self.expand_move(parent_id, best_alt_idx)

                        if child_id is not None and child_id >= 0:
                            path.append((parent_id, best_alt_idx))
                            node_id = child_id
                            direction = 'FORWARD'
                            continue

                    node_id = parent_id

        except KeyboardInterrupt:
            print('\nInterrupted')
        finally:
            for nid, _ in reversed(path):
                self.backprop_node(nid)
            self.save_epd()
            shutil.copy(f'/content/{EPD}', f'{DIR}{EPD}')
            self.engine.shut_down()

# Cell 7: Run
tree = Tree()
tree.yoyo()